version: '3.4'

services:
  ddd_test.customer.api:
    image: ${DOCKER_REGISTRY-}dddtestcustomerapi
    build:
      context: .
      dockerfile: ddd_test.customer.api/Dockerfile

  eventstore.customer:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true # let eventstore run without ceritficate
      - EVENTSTORE_EXT_TCP_PORT=11130 # set internal tcp port
      - EVENTSTORE_HTTP_PORT=21130 # set internal admin ui port
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "11130:11130" # map internal tcp port
      - "21130:21130" # map internal admin ui port
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore

volumes:
  eventstore-data:
  eventstore-logs: